modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "limitedanarchy"
version = "${version}"
displayName = "LimitedAnarchy"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.limitedanarchy]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limitedanarchy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limitedanarchy]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.limitedanarchy]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${ftblibraryversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.limitedanarchy]]
modId = "ftbteams"
mandatory = true
versionRange = "[${ftbteamsversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.limitedanarchy]]
modId = "ftbchunks"
mandatory = true
versionRange = "[${ftbchunksversion},)"
ordering = "AFTER"
side = "BOTH"
